apiVersion: v1
kind: Namespace
metadata:
  name: temporal
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tessera-temporal-db
  namespace: temporal
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: tessera-temporal-db
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: 'rds!db-014345e3-6da3-4f11-ac89-449cbf2c7a77'
        property: password