temporal:
  server:
    config:
      logLevel: info

      persistence:
        defaultStore: default
        visibilityStore: visibility
        numHistoryShards: 512

        datastores:
          default:
            sql:
              createDatabase: true
              manageSchema: true
              pluginName: postgres12
              driverName: postgres12
              databaseName: temporal
              connectAddr: "tessera-temporal.crycm2k0cz7d.us-east-2.rds.amazonaws.com:5432"
              connectProtocol: tcp
              user: postgres
              existingSecret: tessera-temporal-db
              secretKey: password
              maxConns: 20
              maxIdleConns: 20
              maxConnLifetime: "1h"
              tls:
                enabled: true
                enableHostVerification: false

          visibility:
            sql:
              createDatabase: true
              manageSchema: true
              pluginName: postgres12
              driverName: postgres12
              databaseName: temporal_visibility
              connectAddr: "tessera-temporal.crycm2k0cz7d.us-east-2.rds.amazonaws.com:5432"
              connectProtocol: tcp
              user: postgres
              existingSecret: tessera-temporal-db
              secretKey: password
              maxConns: 20
              maxIdleConns: 20
              maxConnLifetime: "1h"
              tls:
                enabled: true
                enableHostVerification: false

    frontend:
      resources:
        requests: { cpu: 50m, memory: 256Mi }
        limits:   { memory: 512Mi }
    history:
      resources:
        requests: { cpu: 50m, memory: 256Mi }
        limits:   { memory: 512Mi }
    matching:
      resources:
        requests: { cpu: 50m, memory: 256Mi }
        limits:   { memory: 512Mi }
    worker:
      resources:
        requests: { cpu: 50m, memory: 256Mi }
        limits:   { memory: 512Mi }

  shims:
    dockerize: false
    elasticsearchTool: false

  web:
    enabled: true

  admintools:
    enabled: true