apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "slack-bot.fullname" . }}
  labels:
    {{- include "slack-bot.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}

  secretStoreRef:
    kind: {{ .Values.externalSecrets.storeRef.kind }}
    name: {{ .Values.externalSecrets.storeRef.name }}

  target:
    name: {{ include "slack-bot.fullname" . }}
    creationPolicy: Owner

  data:
    - secretKey: SLACK_BOT_TOKEN
      remoteRef:
        key: tessera/slack-bot-token

    - secretKey: SLACK_APP_TOKEN
      remoteRef:
        key: tessera/slack-app-token